### ISSUE TITLE
CONDITIONS_MAP is missing key halfbewolkt_regen

### ISSUE THREAD

**Issue by golles** [golles/ha-knmi#2]
## Version of the custom_component

1.0.2

## Describe the bug
`CONDITIONS_MAP` is missing `halfbewolkt_regen`

## Debug log

```text
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 615, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 404, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 180, in state_attributes
    if self.forecast is not None:
  File "/config/custom_components/knmi/weather.py", line 93, in forecast
    ATTR_FORECAST_CONDITION: CONDITIONS_MAP[
KeyError: 'halfbewolkt_regen'
```

**Comment by golles** [comment]
Contacted API provider to see if there are more options missing in their docs.
