### ISSUE TITLE
Error installing custom component 

### ISSUE THREAD

**Issue by kabouterkrant** [golles/ha-knmi#37]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

After an update , not sure which one, I decided to reinstall the knmi integration using HACS. Trying to add integration in Homeassistant I'm getting the following message:

Error
This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.

Older versions of this component/HA worked fine.

### What version of this integration has the issue?

1.2.0

### What version of Home Assistant Core has the issue?

core 2022.7.0 or higher

### Home Assistant log

```shell
2022-07-22 09:16:19 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration knmi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-22 09:16:19 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-22 09:16:19 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-22 09:16:19 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration nefiteasy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-22 09:16:19 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration afvalwijzer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-22 09:16:19 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration buienalarm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-22 09:17:06 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.knmi.config_flow
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 618, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 635, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/knmi/__init__.py", line 83, in <module>
    class KnmiDataUpdateCoordinator(DataUpdateCoordinator):
  File "/home/homeassistant/.homeassistant/custom_components/knmi/__init__.py", line 107, in KnmiDataUpdateCoordinator
    ) -> float | int | str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
2022-07-22 09:17:06 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration knmi: Exception importing custom_components.knmi.config_flow
```

**Comment by golles** [comment]
Hi @kabouterkrant, I can't reproduce this issue on a devcontainer nor in my production HA.

The `TypeError` from your log, was added in `1.2.0` of this component.

From my own experience, I remember that config flow issues can mean 2 things:
1. Not all the files are present (you can compare the files on your system with the list mentioned: https://github.com/golles/ha-knmi#manual)
2. During uninstalling and installing something goes wrong

You can try to fix the latter by deleting this integration, restarting Home Assistant, and adding the integration again.
Let me know if this helps, else I might need more info to understand what is going wrong.

**Comment by golles** [comment]
Can you provide me with your system info, you can find it here: https://my.home-assistant.io/redirect/system_health/

It looks like this:
```
Versie | core-2022.7.6
-- | --
Type installatie | Home Assistant Container
Ontwikkeling | false
Supervisor | false
Docker | true
Gebruiker | root
Virtuele omgeving | false
Python-versie | 3.10.5
Besturingssysteem | Linux
Versie van het besturingssysteem | 5.4.0-121-generic
CPU-architectuur | x86_64
Tijdzone | Europe/Amsterdam
Configuration Directory | /config
```

**Comment by baahver** [comment]
Hi Golles, 
I have exactly the same problem as kabouterkrant.
I installed via hacs. 

```
Versie | core-2022.7.6
-- | --
Type installatie | Home Assistant Core
Ontwikkeling | false
Supervisor | false
Docker | false
Gebruiker | homeassistant
Virtuele omgeving | true
Python-versie | 3.9.7
Besturingssysteem | Linux
Versie van het besturingssysteem | 5.13.0-52-generic
CPU-architectuur | x86_64
Tijdzone | Europe/Amsterdam
Configuration Directory | /home/homeassistant/.homeassistant
```
When I add the intregration I get a message: 

```
Deze integratie ondersteunt geen configuratie via de UI. Als u deze link van de Home Assistant-website hebt gevolgd, zorg er dan voor dat u de nieuwste versie van Home Assistant heeft draaien.```

**Comment by golles** [comment]
Thanks, @baahver I see what the issue is. I'm using a Python [feature](https://docs.python.org/3.10/whatsnew/3.10.html#pep-604-new-type-union-operator) that was added in version 3.10.

I assumed this should be fine, as Home Assitant updated to python 3.10 in 2022.7 (https://www.home-assistant.io/blog/2022/07/06/release-20227/#improved-stability-and-performance-and-python-310).

I did set the minimal Home Assistant version for this component to 2022.7 as well https://github.com/golles/ha-knmi/blob/main/hacs.json#L3

So I do wonder how it's possible that both of you (and maybe more people) are on HA 2022.7 and still have Python version 3.9

**Comment by baahver** [comment]
well, version 1.1.11 was working well on python3.9. 
But I updatet my server from Ubuntu 21.10 to LTS 22.04. And there 3.10 is included.
Now 1.2 is working too. ;)
Thank you

**Comment by kabouterkrant** [comment]
<html>
<body>


Version | core-2022.7.6
-- | --
Installation Type | Home Assistant Core
Development | false
Supervisor | false
Docker | false
User | homeassistant
Virtual Environment | true
Python Version | 3.9.13
Operating System Family | Linux
Operating System Version | 5.10.103-v8+
CPU Architecture | aarch64
Timezone | UTC
Configuration Directory | /home/homeassistant/.homeassistant


</body>
</html>

Looks like my python is also version 3.9...

**Comment by kabouterkrant** [comment]
Looks like both version 3.9 and 3.10 are installed on my pi with debian testing, No clue how to use the right version.

**Comment by baahver** [comment]
Are you using core on Ubuntu?

**Comment by kabouterkrant** [comment]
No. I'm using debian on a pi 4.

**Comment by baahver** [comment]
On Ubuntu I've done: 
```
sudo su
systemctl stop home-assistant@homeassistant
apt update
apt install python3.10 python3.10-dev python3.10-venv
cd /srv
mv homeassistant homeassistant_old
mkdir homeassistant
chown homeassistant:homeassistant homeassistant
sudo -u homeassistant -H -s
cd /srv/homeassistant
python3.10 -m venv .
source bin/activate
python3 -m pip install wheel
pip3 install homeassistant
systemctl start home-assistant@homeassistant
```
I assume that debian will be almost the same.

**Comment by kabouterkrant** [comment]
It worked. Changed my python environment to 3.10 and the integration installed smoothly. Thanks.!

**Comment by golles** [comment]
Happy to read that you both managed to resolve the issue and thank you @baahver for helping @kabouterkrant, as a docker user I wouldn't have been able to help with the upgrade guide.
