### ISSUE TITLE
Time out issue?

### ISSUE THREAD

**Issue by haaino** [golles/ha-knmi#38]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

I’m getting the following warnings and error in my logfile
——-
This error originated from a custom integration.
```
Logger: homeassistant
Source: custom_components/knmi/binary_sensor.py:142 
Integration: KNMI (documentation, issues) 
First occurred: 11:30:11 (5 occurrences) 
Last logged: 19:30:12

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 348, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 209, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/knmi/binary_sensor.py", line 106, in is_on
    sunrise = self.time_as_datetime(self.coordinator.get_value("sup"))
  File "/config/custom_components/knmi/binary_sensor.py", line 142, in time_as_datetime
    time_array = time.split(":")
AttributeError: 'NoneType' object has no attribute 'split'
```
And at the same time
```
This error originated from a custom integration.

Logger: custom_components.knmi
Source: custom_components/knmi/api.py:29 
Integration: KNMI (documentation, issues) 
First occurred: 11:30:11 (5 occurrences) 
Last logged: 19:30:12

Error fetching information from http://weerlive.nl/api/json-data-10min.php?key=Numbers&cd4&locatie=52.,bunch of numbers - Cannot connect to host weerlive.nl:80 ssl:default [Network unreachable]

```

### What version of this integration has the issue?

Latest

### What version of Home Assistant Core has the issue?

2022.8.2

### Additional information

I think it has to do with the fact that the host was unreachable?

**Comment by golles** [comment]
This does look like an issue with the request, however, I didn't experience this myself.
Is this still happening for you, or is it now working fine?

**Comment by haaino** [comment]
For now it is working fine again. I will let you know if it happens again.
