### ISSUE TITLE
 'utf-8' codec can't decode byte 0xeb in position 38: invalid continuation byte

### ISSUE THREAD

**Issue by yfands** [golles/ha-knmi#4]
## Version of the knmi custom_component
VERSION = "1.0.6"

## Describe the bug
Installed for the first time KNMI integration, with following error
(Entities could also NOT be created.)

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.knmi
Source: custom_components/knmi/api.py:68
Integration: KNMI (documentation, issues)
First occurred: 00:52:54 (1 occurrences)
Last logged: 00:52:54

Something really wrong happened! - 'utf-8' codec can't decode byte 0xeb in position 38: invalid continuation byte

## Debug log

```text

Logger: homeassistant.components.weather
Source: custom_components/knmi/weather.py:35
Integration: Weather (documentation, issues)
First occurred: 00:53:00 (2 occurrences)
Last logged: 00:53:01

Error adding entities for domain weather with platform knmi
Error while setting up knmi platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 447, in _async_add_entity
    suggested_object_id = entity.name  # type: ignore[unreachable]
  File "/config/custom_components/knmi/weather.py", line 35, in name
    location = self.coordinator.data["plaats"]
TypeError: 'NoneType' object is not subscriptable


```

**Comment by yfands** [comment]
No reaction, No comment. from developer???
Time to unistall I guess

**Comment by golles** [comment]
> No reaction, No comment. from developer???
> Time to unistall I guess

I could write a whole message about that I made this in my spare time and share this with others so they don't have to make this themselves and like most of us, I also go on vacation. But I guess with your attitude that would be a waste of my time.

If you still want me to look into this, then let me know, I have some questions about reproducibility.
