### ISSUE TITLE
‘NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by haaino** [golles/ha-knmi#45]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

meassistant
Source: custom_components/knmi/binary_sensor.py:142 
Integration: KNMI ([documentation](https://github.com/golles/ha-knmi/blob/main/README.md), [issues](https://github.com/golles/ha-knmi/issues)) 
First occurred: 11 November 2022 at 16:17:50 (1 occurrences) 
Last logged: 11 November 2022 at 16:17:50

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 348, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 211, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/knmi/binary_sensor.py", line 106, in is_on
    sunrise = self.time_as_datetime(self.coordinator.get_value("sup"))
  File "/config/custom_components/knmi/binary_sensor.py", line 142, in time_as_datetime
    time_array = time.split(":")
AttributeError: 'NoneType' object has no attribute 'split'

### What version of this integration has the issue?

1.3.0

### What version of Home Assistant Core has the issue?

2022.11.2

**Comment by golles** [comment]
Thanks for reporting, this is now fixed by #46, and will be released as `1.3.1`
I think there was a glitch in retrieving data (or an issue on the server), If I'm not mistaken it would have automatically recovered from the problem.

The next time, please fill in the bug template appropriately, by filling in all fields and the correct fields. Thanks!
