### ISSUE TITLE
Integration doesn’t automatically start after HA restart

### ISSUE THREAD

**Issue by groenmarsmannetje** [golles/ha-knmi#7]
## Configuration

```yaml

Add your logs here.

```

## Describe the bug
When I restart Home Assistant then the KNMI integration doesn’t seem to automatically start. After full restart of HA i have to manually start it with reloading the integration.

## Debug log

```text

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/knmi/sensor.py", line 12, in async_setup_entry
    sensors.append(KnmiSensor(coordinator, entry, sensor["name"], sensor["unit"], sensor["icon"], sensor["key"]))
  File "/config/custom_components/knmi/sensor.py", line 25, in __init__
    self.location_name = self.coordinator.data["plaats"]
TypeError: 'NoneType' object is not subscriptable

```

**Comment by golles** [comment]
The problem is that no data has been retrieved from the API. I need to see what I could do about this.

Which version of the component are you using?

**Comment by groenmarsmannetje** [comment]
> The problem is that no data has been retrieved from the API. I need to see what I could do about this.
> 
> Which version of the component are you using?

I am using version d413064

**Comment by frank8the9tank** [comment]
I'm running version: b2ffed1 and having exactly the same thing.
When HA restart the interation always shows no data,
Then when i reload the intergation manual trough the dashboard the integration works fine.

**Comment by golles** [comment]
Could one of you provide some startup logs from when this occurs? 
Please make sure debug logs are enabled in your `logger`, for example like:
```yaml
logger:
  default: warn # Or anything else you've set this to
  logs:
    custom_components.knmi: debug
```
https://www.home-assistant.io/integrations/logger/

**Comment by groenmarsmannetje** [comment]
> Could one of you provide some startup logs from when this occurs? Please make sure debug logs are enabled in your `logger`, 

After a restart with debug logging on for knmi component, the following errors and warnings are recorded for the knmi component.

````
2021-12-23 14:28:36 WARNING (SyncWorker_10) [homeassistant.loader] We found a custom integration knmi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-23 14:29:30 ERROR (MainThread) [custom_components.knmi] Timeout error fetching information from http://weerlive.nl/api/json-data-10min.php?key=4508f0324a&locatie=52.12835,4.672005 - 
2021-12-23 14:29:30 DEBUG (MainThread) [custom_components.knmi] Finished fetching knmi data in 11.851 seconds (success: True)
2021-12-23 14:29:38 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up knmi platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/knmi/binary_sensor.py", line 18, in async_setup_entry
    KnmiBinarySensor(
  File "/config/custom_components/knmi/binary_sensor.py", line 47, in __init__
    self.location_name = self.coordinator.data["plaats"]
TypeError: 'NoneType' object is not subscriptable
2021-12-23 14:29:41 ERROR (MainThread) [homeassistant.components.weather] Error adding entities for domain weather with platform knmi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in _async_add_entity
    if entity.unique_id is not None:
  File "/config/custom_components/knmi/entity.py", line 16, in unique_id
    return f"{self.config_entry.entry_id}-{self.name}"
  File "/config/custom_components/knmi/weather.py", line 35, in name
    location = self.coordinator.data["plaats"]
TypeError: 'NoneType' object is not subscriptable
2021-12-23 14:29:41 ERROR (MainThread) [homeassistant.components.weather] Error while setting up knmi platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in _async_add_entity
    if entity.unique_id is not None:
  File "/config/custom_components/knmi/entity.py", line 16, in unique_id
    return f"{self.config_entry.entry_id}-{self.name}"
  File "/config/custom_components/knmi/weather.py", line 35, in name
    location = self.coordinator.data["plaats"]
TypeError: 'NoneType' object is not subscriptable
2021-12-23 14:31:01 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up knmi platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/knmi/sensor.py", line 13, in async_setup_entry
    KnmiSensor(
  File "/config/custom_components/knmi/sensor.py", line 44, in __init__
    self.location_name = self.coordinator.data["plaats"]
TypeError: 'NoneType' object is not subscriptable
````

**Comment by golles** [comment]
Thanks!

You are right, there is indeed a 10 seconds timeout set in the api: https://github.com/golles/ha-knmi/blob/main/custom_components/knmi/api.py#L9
This might be a bit too short.

Can you check the start time of the KNMI Integration? You can see that on this page: https://my.home-assistant.io/redirect/info/ 
If that is more than 10 seconds, than we know for sure this is the problem. For me it takes 4 seconds to load.

I do agree that the state should become "unavailable" if there is an issue with the api, or when the timeout kicks in.

I'll try to get it fixed soon, hopefully before the holidays.

**Comment by groenmarsmannetje** [comment]
See below

![image](https://user-images.githubusercontent.com/46958454/147265826-73a7602d-5d72-499d-bad1-4634b8c05e89.png)

**Comment by golles** [comment]
Oeh, I was considering changing the timeout to 30 seconds as a temporary quick fix, but that wouldn't catch it in your case. 
I'm quite surprised to see such a long setup time in your HA.

**Comment by golles** [comment]
I have a PR with a fix ready, I need to do a bit more testing before I can merge it.

This will be a breaking change, which means users need to remove the integration and add it again, as sensors will be created with the given name and not the name coming from the API, as this can fail...

Would you be able to test the branch in #13 and report any issues?

**Comment by frank8the9tank** [comment]
I have updated to the latest 1.1.4, and removed/re-added the integration,
Will check it the coming restarts of HA.

**Comment by golles** [comment]
> I have updated to the latest 1.1.4, and removed/re-added the integration, Will check it the coming restarts of HA.

Cool. I see that is a little confusing as well, I updated the version tag in that branch to 1.1.5 (81b23607bb8ff3882603cee6208f62539f9c7fd5)

**Comment by groenmarsmannetje** [comment]
I have installed version 1.1.4 too and first restart worked without issue. I do not see version 1.1.5 yet. But as soon as that is available I will try that one too and report back.

**Comment by golles** [comment]
1.1.5 is only available in the branch I mentioned. Not in the releases yet, as I haven't build the release.

**Comment by frank8the9tank** [comment]
Have not seen the problem again, so at startup of HA the integration is showing weather data.

**Comment by golles** [comment]
> Have not seen the problem again, so at startup of HA the integration is showing weather data.

Good to hear, I've also had this version running for a couple of days and haven't seen any issues. Will merge the branch and make the 1.1.5 release.
Thank you to both of you, for all the information and testing!

**Comment by groenmarsmannetje** [comment]
I followed the instruction and it worked as a glance. Thank you.
