### ISSUE TITLE
Value dauwp can't be converted to class float

### ISSUE THREAD

**Issue by dhover** [golles/ha-knmi#99]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

The custom component produces a warning when dauwp is not available.
The api returns: "dauwp": "onb." which cannot converted to float.

### Integration version

1.6.1

### Home Assistant version

core-2023.10.5

### Python version

3.11.5

### Home Assistant log

```shell
2023-10-29 07:41:32.569 WARNING (MainThread) [custom_components.knmi] Value dauwp can't be converted to <class 'float'>
2023-10-29 07:42:02.141 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 593, in state
numerical_value = float(value) # type:ignore[arg-type]
^^^^^^^^^^^^
ValueError: could not convert string to float: 'onb.'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
self.async_update_listeners()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
state, attr = self._async_generate_attributes()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 820, in _async_generate_attributes
state = self._stringify_state(available)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 785, in _stringify_state
if (state := self.state) is None:
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 595, in state
raise ValueError(
ValueError: Sensor sensor.knmi_markelo_dauwpunt has device class 'temperature', state class 'measurement' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'onb.' (<class 'str'>)
2023-10-29 07:42:02.569 WARNING (MainThread) [custom_components.knmi] Value dauwp can't be converted to <class 'float'>
```

**Comment by golles** [comment]
This is a warning that the sensor wasn't receiving a numeric value from the API, looks like this has recovered.
If you see this again today, let me know and I contact the supplier. Will close this for now.
